$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

# Metadata for the pipeline
display_name: train_vehicle_price_prediction_pipeline  
experiment_name: vehicle_price_prediction_experiment  
description: Pipeline to train and register a RandomForest model for vehicle price prediction  

# Define the inputs for the pipeline
inputs:
  data:
    type: uri_file
    path: azureml:used-cars-data@latest

# Define the outputs for the pipeline
outputs:
  train_data:
    type: uri_folder  
  test_data:
    type: uri_folder  
  model_info_output_path:
    type: uri_folder  

# Settings for the pipeline execution
settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

# Define the jobs in the pipeline
jobs:
  # Data preparation job
  prep_data:
    name: prep_data_job  
    display_name: Data Preparation  
    code: ../../../data-science/src
    command: >-
      python prep.py  
      --data ${{inputs.data}} 
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}} 
    environment: azureml:used-cars-train-env@latest
    inputs:
      data: ${{parent.inputs.data}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}
  
  # Hyperparameter tuning job
  sweep_step:
    name: sweep_step_job
    display_name: Hyperparameter Tuning 
    type: sweep
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: mlflow_model
    sampling_algorithm: random 
    trial: ./train.yml  
    search_space:
      n_estimators:
        type: choice
        values: ["10", "25", "75", "100", "125", "150", "175", "200"]
      max_depth:
        type: choice  
        values: ["2", "5", "10", "15", "20", None]  
    objective:
      goal: minimize
      primary_metric: MSE
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200

  # Model registration job
  register_model:
    name: register_model_job  
    display_name: Model Registration  
    code: ../../../data-science/src
    command: >-
      python register.py 
      --model_name ${{inputs.model_name}} 
      --model_path ${{inputs.model_path}} 
      --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:used-cars-train-env@latest
    inputs:
      model_name: "used_cars_price_prediction_model"
      model_path: ${{parent.jobs.sweep_step.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}

